version: '3.8'
services:
  # Django App
  backend_auth:
   container_name: solopython_ms_auth
   build: .
   volumes:
    - .:/app
   ports:
    - 8000:8000
   depends_on:
    - db
    - redis
  
  # Event Queue Kafka
  queue_auth:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db
  
  # Database (PostgreSQL)
  db:
   image: postgres
   container_name: django_auth_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_auth_db
      POSTGRES_USER: solopython
      POSTGRES_PASSWORD: postgres
   ports:
    - 5432:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: django_auth_api_redis
    ports:
      - 6379:6379