version: '3.8'
services:
  # Django App
  backend_products:
   container_name: solopython_ms_products
   build: .
   command: >
      sh -c "python manage.py runserver 0.0.0.0:8006"
   volumes:
    - .:/app
   ports:
    - 8006:8006
   depends_on:
    - db_products
    - redis
  
  # # Event Queue Kafka
  # queue_products:
  #   build: .
  #   command: >
  #     sh -c "python consumer.py"
  #   depends_on:
  #     - db_products
  
  # Database (PostgreSQL)
  db_products:
   image: postgres
   container_name: django_products_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_products_db
      POSTGRES_USER: solopython
      POSTGRES_PASSWORD: postgres
   ports:
    - 5437:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: django_products_api_redis
    ports:
      - 6384:6379