# Generated by Django 3.2.16 on 2023-03-03 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.IntegerField(unique=True)),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('decimals', models.IntegerField()),
                ('icon_url', models.URLField(blank=True)),
                ('is_custom', models.BooleanField(blank=True, default=False)),
                ('network', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens', models.ManyToManyField(blank=True, to='tokens.Token')),
            ],
        ),
        migrations.CreateModel(
            name='NFTList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('nfts', models.ManyToManyField(blank=True, to='tokens.NFT')),
            ],
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='tokens.token')),
            ],
            options={
                'unique_together': {('wallet', 'token')},
            },
        ),
    ]
