# Generated by Django 3.2.16 on 2023-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
