# Generated by Django 3.2.16 on 2023-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_nft_transaction_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenlist',
            old_name='wallet',
            new_name='address',
        ),
    ]
