version: '3.8'
services:
  # Django App
  backend_cryptocurrency:
   container_name: solopython_ms_cryptocurrency
   build: .
   command: >
      sh -c "python manage.py runserver 0.0.0.0:8005"
   volumes:
    - .:/app
   ports:
    - 8005:8005
   depends_on:
    - db_cryptocurrency
    - redis
  
  # Event Queue Kafka
  queue_cryptocurrency:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_cryptocurrency
  
  # Database (PostgreSQL)
  db_cryptocurrency:
   image: postgres
   container_name: django_cryptocurrency_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_cryptocurrency_db
      POSTGRES_USER: solopython
      POSTGRES_PASSWORD: postgres
   ports:
    - 5435:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  # Redis Cache
  redis:
    image: redis
    container_name: django_cryptocurrency_api_redis
    ports:
      - 6382:6379