# Generated by Django 3.2.16 on 2023-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
