# Generated by Django 3.2.16 on 2023-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
