# Generated by Django 3.2.16 on 2023-01-23 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.UUIDField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping List',
            },
        ),
    ]
